version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    networks:
      - calculadora-net

  servico-soma:
    build: ./servico-soma
    container_name: servico-soma
    ports:
      - "8001:8001"
    networks:
      - calculadora-net

  servico-subtracao:
    build: ./servico-subtracao
    container_name: servico-subtracao
    ports:
      - "8002:8002"
    networks:
      - calculadora-net

  servico-multiplicacao:
    build: ./servico-multiplicacao
    container_name: servico-multiplicacao
    ports:
      - "8003:8003"
    networks:
      - calculadora-net

  servico-divisao:
    build: ./servico-divisao
    container_name: servico-divisao
    ports:
      - "8004:8004"
    networks:
      - calculadora-net

networks:
  calculadora-net:
    driver: bridge