version: '3.8'

networks:
  calculadora-net:
    driver: bridge

services:
  # ==========================================
  # INTERFACE E ROTEAMENTO (API GATEWAY)
  # ==========================================
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - soma
      - subtracao
      - multiplicacao
      - divisao
    networks:
      - calculadora-net

  # ==========================================
  # MICROSSERVIÇOS DE OPERAÇÃO
  # ==========================================
  soma:
    build: ./servico-soma
    container_name: servico-soma
    ports:
      - "8001:8001"
    networks:
      - calculadora-net

  subtracao:
    build: ./servico-subtracao
    container_name: servico-subtracao
    ports:
      - "8002:8002"
    networks:
      - calculadora-net

  multiplicacao:
    build: ./servico-multiplicacao
    container_name: servico-multiplicacao
    ports:
      - "8003:8003"
    networks:
      - calculadora-net

  divisao:
    build: ./servico-divisao
    container_name: servico-divisao
    ports:
      - "8004:8004"
    networks:
      - calculadora-net

  # ==========================================
  # INFRAESTRUTURA DE MONITORAMENTO (DASHBOARD)
  # ==========================================
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - calculadora-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor
    networks:
      - calculadora-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Senha padrão para os testes
    depends_on:
      - prometheus
    networks:
      - calculadora-net